# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Han-B/Lab_FinalA/Lab_FinalA.cache/wt [current_project]
set_property parent.project_path C:/Users/Han-B/Lab_FinalA/Lab_FinalA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Han-B/Lab_FinalA/Lab_FinalA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  C:/Users/Han-B/Lab_FinalA/Lab_FinalA.srcs/sources_1/imports/new/full_imem.mem
  C:/Users/Han-B/Lab_FinalA/Lab_FinalA.srcs/sources_1/imports/new/full_dmem.mem
  C:/Users/Han-B/Lab_FinalA/Lab_FinalA.srcs/sources_1/imports/new/mem_data.mem
  C:/Users/Han-B/Lab_FinalA/Lab_FinalA.srcs/sources_1/imports/new/sqr_imem.mem
  C:/Users/Han-B/Lab_FinalA/Lab_FinalA.srcs/sources_1/imports/new/sqr_dmem.mem
}
read_verilog -library xil_defaultlib -sv C:/Users/Han-B/Lab_FinalA/Lab_FinalA.srcs/sources_1/new/sound.sv
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top music -part xc7a100tcsg324-1


write_checkpoint -force -noxdef music.dcp

catch { report_utilization -file music_utilization_synth.rpt -pb music_utilization_synth.pb }
